### ISSUE TITLE
Buttons in bottomView don't seem to work

### ISSUE THREAD

**Issue by v-ken** [Ramotion/elongation-preview#1]
Adding a button to the cell's bottomView doesn't seem to respond to taps. Any ideas on what's causing this?

**Comment by v-ken** [comment]
Found a solution which is to override `hitTest` in the `ElongationCell` subclass:


    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        let scalableViewContainsPoint = scalableView.frame.contains(point)
        let backViewContainsPoint = bottomView.frame.contains(point)
        
        if scalableViewContainsPoint {
            return scalableView.hitTest(convert(point, to: scalableView), with: event)
        }
        
        if backViewContainsPoint {
            return bottomView.hitTest(convert(point, to: bottomView), with: event)
        }
        return nil
    }


Note the recursive call to `hitTest` from `scalableView` and `bottomView`

**Comment by av0c0der** [comment]
@v-ken thank you. If you want to contribute, please, make PR request and I'll merge it. Note that you need to change this method both in `ElongationCell` & `ElongationHeader` files.

**Comment by v-ken** [comment]
@Jauzee Thanks for the quick response. Unfortunately I don't think it's that simple. The solution I posted may cause adverse effects to `gestureRecognizerSwiped` implementation in `ElongationViewController`. The overridden `hitTest` in the cell was explicitly returning `scalableView` and `bottomView` which is then used here:

https://github.com/Ramotion/elongation-preview/blob/master/ElongationPreview/Source/ViewControllers/ElongationViewController.swift#L265-L293

I don't yet have a solution for this at this stage.

**Comment by v-ken** [comment]
Just created a pull request:
https://github.com/Ramotion/elongation-preview/pull/2

**Comment by av0c0der** [comment]
@v-ken thank you for contributing!
