### ISSUE TITLE
Crash:Can't get `ElongationViewController` from UINavigationController nor from context's viewController itself.

### ISSUE THREAD

**Issue by Stefania66** [Ramotion/elongation-preview#13]
Buonasera, ho inserito la libreria Elongation Prewiew nel mio progetto, ma mi da questo errore: Can't get `ElongationViewController` from UINavigationController nor from context's viewController itself.
Cosa  devo fare? Grazie da Stefania

**Comment by thiagobessa1** [comment]
Can you solve it?

**Comment by Stefania66** [comment]
Ciao. Non ci sono riuscita.
Stefania

> Il giorno 04 mag 2018, alle ore 23:54, ThiagB <notifications@github.com> ha scritto:
> 
> Can you solve it?

**Comment by 0ber** [comment]
@Stefania66 How did you received this error?

**Comment by Stefania66** [comment]
Ciao ho nel mio progetto librerie  Paper Onboarding e il menu SSASideMenu. Se metto la libreria ElongiationPrewiew in un progetto nuovo funziona, se lo inserisco dove sono le due librerie sopra citate e lo faccio partire crasha con quell’errore.

Ciao se vuoi ti faccio un piccolo video per farti vedere? Grazie

**Comment by 0ber** [comment]
@Stefania66 Could you write in English?

**Comment by Stefania66** [comment]
Hi, I have in my project the Paper Onboarding libraries and the SSASideMenu menu. If I put the ElongiationPrewiew library in a new project it works, if I insert it where are the two above mentioned libraries and I will have it locked with that error.
Sorry but with English I'm not very good.
Hello, if you want, I'll do a little video to show you? Thank you

**Comment by 0ber** [comment]
Duplicate of #6
