### ISSUE TITLE
Does it work with Navigation Controller?

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [Ramotion/elongation-preview#3]
I tried adding Navigation Controller to Demo project and the detail view transition doesn't seem to be happening.

And thanks for this wonderful work :)

**Comment by av0c0der** [comment]
@AnnieNinaJoyceV you're welcome!

This control wasn't designed to use within `UINavigationController`. Maybe there is a reason make it available to embed `ElongationViewController` to navigation stack, but I'm not sure about `ElongationDetailViewController` (the second one).

**Comment by AnnieNinaJoyceV** [comment]
@Jauzee I got it working by Tweaking `func root(from context: UIViewControllerContextTransitioning) -> ElongationViewController`
This works for me with UINavigationController - Navigation Bar hidden. I just wanted to know confirm whether there is some other approach. Thanks for your response.

`fileprivate func root(from context: UIViewControllerContextTransitioning) -> ElongationViewController {
    guard let c = context.viewController(forKey: rootKey) else {
        return context.viewController(forKey: rootKey) as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
        }
        if (c.isKind(of: UINavigationController.self)) {
            guard let nv = c as? UINavigationController else {
                return context.viewController(forKey: rootKey) as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
            }
            let v = nv.topViewController
            return v as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
        }
        return context.viewController(forKey: rootKey) as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
    }`

**Comment by av0c0der** [comment]
@AnnieNinaJoyceV, sorry for the delay. You did it in very complex way. We'll look on that.

**Comment by AnnieNinaJoyceV** [comment]
@Jauzee No problem, it works for me right now. I will wait for your solution to this.

**Comment by av0c0der** [comment]
@AnnieNinaJoyceV fixed this issue in `1.0.4`.

Actually we'll just check if there is an UINavigationContoller and if so we'll iterate over `viewControllers` looking for `ElongationViewController`.

**Comment by sasquatchgit** [comment]
@AnnieNinaJoyceV  code but formatted:
```swift
fileprivate func root(from context: UIViewControllerContextTransitioning) -> ElongationViewController {
        guard let c = context.viewController(forKey: rootKey) else {
            return context.viewController(forKey: rootKey) as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
            
        }
        if (c.isKind(of: UINavigationController.self)) {
            guard let nv = c as? UINavigationController else {
                return context.viewController(forKey: rootKey) as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
            }
            let v = nv.topViewController
            return v as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
        }
        return context.viewController(forKey: rootKey) as? ElongationViewController ?? ElongationViewController(nibName: nil, bundle: nil)
        
    }
```

**Comment by kunwar231** [comment]
how to show navigation bar on ElongationDetailViewController?
