### ISSUE TITLE
Button action not being fired from the bottom view.

### ISSUE THREAD

**Issue by jsdu** [Ramotion/elongation-preview#5]
I tried adding a button to the bottom view and noticed that if I normal tap, the button action is not being triggered. I tried adding this code to the SwipeableTableViewController but it still does not seem to encapsulate the button touch. 

public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        if (touch.view is UIButton) {
            return false
        }
        return true
    }

**Comment by av0c0der** [comment]
@jsdu please checkout this archive [elongation-preview-button-demo.zip](https://github.com/Ramotion/elongation-preview/files/999224/elongation-preview-button-demo.zip).
